config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cart#show"
  
  # Item Routes
  get "/catalog" => "items#index",
    as: "catalog"
  get "/catalog/new" => "items#new",
    as: "new_item"
  post "/catalog" => "items#create",
    as: "create_item"
  delete "/items/:id" => "items#destroy",
    as: "delete_item"
  
  # Cart Routes
  get "/cart" => "cart#show",
    as: "cart"
  get "/reset"=> "cart#destroy",
    as: "reset"

  # Checkout Items Routes
  post "/checkout_items" => "checkout_items#create",
    as: "create_checkout_item"
  delete "/checkout_items/:id" => "checkout_items#destroy",
    as: "delete_checkout_item"
  
  # Free Items Routes
  get "/free_items" => "free_items#index",
    as: "free_items"
  get "/free_items/new" => "free_items#new",
    as: "new_free_item"
  post "/free_items" => "free_items#create",
    as: "create_free_item"
  delete "/free_items/:id" => "free_items#destroy",
    as: "delete_free_item"

  # Bulk Orders Routes
  get "/bulk_orders" => "bulk_orders#index",
    as: "bulk_orders"
  get "/bulk_orders/new" => "bulk_orders#new",
    as: "new_bulk_order"
  post "/bulk_orders" => "bulk_orders#create",
    as: "create_bulk_order"
  delete "/bulk_orders/:id" => "bulk_orders#destroy",
    as: "delete_bulk_order"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bulk_order.rb
class BulkOrder < ApplicationRecord
    validates :min_quantity, presence: true
    validates :adjusted_price, presence: true

    belongs_to :item
end

app/models/checkout.rb
class Checkout < ApplicationRecord
    has_many :checkout_items, dependent: :destroy
    before_save :get_free_items
    before_save :set_subtotal
    before_save :set_total

    def subtotal
        checkout_items.collect { |checkout_item| checkout_item.valid? ? checkout_item.item.price : 0 }.sum
    end

    def total
        overall_total = checkout_items.collect { |checkout_item| checkout_item.valid? ? checkout_item.item.price : 0 }.sum
        
        # Pricing Rules for Free Items
        rules_free = Array.new
        FreeItem.all.each do |rule|
            rules_free.push([rule.item_id, rule.quantity, rule.free_item])
        end

        rules_free.each do |rule|
            item_quantity = 0
            
            checkout_items.each do |item|
                if rule[0] == item.item_id
                    item_quantity += 1
                end    
            end

            if item_quantity >= rule[1]
                quantity_of_free = item_quantity / rule[1]

                quantity_in_cart = 0
                checkout_items.each do |item|
                    if item.item_id == Item.where(sku: rule[2]).first.id
                        quantity_in_cart += 1
                    end
                end

                if quantity_in_cart >= quantity_of_free
                    overall_total = overall_total - (quantity_of_free * Item.where(sku: rule[2]).first.price)
                elsif quantity_in_cart < quantity_of_free
                    overall_total = overall_total - (quantity_in_cart * Item.where(sku: rule[2]).first.price)
                end
            end
        end

        # Pricing Rules for Bulk Orders
        rules_bulk = Array.new
        BulkOrder.all.each do |rule|
            rules_bulk.push([rule.item_id, rule.min_quantity, rule.adjusted_price])
        end

        rules_bulk.each do |rule|
            item_quantity = 0

            checkout_items.each do |item|
                if rule[0] == item.item_id
                    item_quantity += 1
                end
            end

            if item_quantity >= rule[1]
                discount_price = Item.where(id: rule[0]).first.price - rule[2]

                overall_total = overall_total - (item_quantity * discount_price)
            end
        end

        overall_total
    end

    private

    def get_free_items
        @free_items_rules = FreeItem.all
    end
    
    def set_subtotal
        self[:subtotal] = subtotal
    end

    def set_total
        self[:total] = total
    end
end

app/models/checkout_item.rb
class CheckoutItem < ApplicationRecord
    belongs_to :item
    belongs_to :checkout
end

app/models/free_item.rb
class FreeItem < ApplicationRecord
    validates :quantity, presence: true
    validates :free_item, presence: true
    
    belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    validates :sku, presence: true,
                    uniqueness: true
    validates :name, presence: true
    validates :price, presence: true

    has_many :checkout_items, dependent: :destroy
    has_many :free_items, dependent: :destroy
    has_many :bulk_orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulk_orders_controller.rb
class BulkOrdersController < ApplicationController
    def index
        @bulk_orders = BulkOrder.all
    end
    
    def new
        @bulk_orders = BulkOrder.all
        @bulk_order = BulkOrder.new
    end
    
    def create
        @bulk_order = BulkOrder.new(bulk_order_params)

        if @bulk_order.save
            redirect_to bulk_orders_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @bulk_order = BulkOrder.find(params[:id])
        @bulk_order.destroy
        redirect_to bulk_orders_path, status: :see_other
    end

    private

    def bulk_order_params
        params.require(:bulk_order).permit(:min_quantity, :item_id, :adjusted_price)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :set_checkout

    def show
        @checkout_items = helpers.current_checkout.checkout_items
        @checkout_item = @checkout.checkout_items.new
    end

    def destroy
        reset_session
        redirect_to cart_path
    end

    private

    def set_checkout
        @checkout = helpers.current_checkout
    end
end

app/controllers/checkout_items_controller.rb
class CheckoutItemsController < ApplicationController
    before_action :set_checkout

    def create
        @checkout_item = @checkout.checkout_items.new(checkout_params)
        @checkout.save
        session[:checkout_id] = @checkout.id

        if @checkout_item.save
            redirect_to cart_path
        else
            redirect_to cart_path, status: :unprocessable_entity
        end
    end

    def destroy
        @checkout_item = @checkout.checkout_items.find(params[:id])
        @checkout_item.destroy
        redirect_to cart_path, status: :see_other
    end

    private

    def set_checkout
        @checkout = helpers.current_checkout
    end

    def checkout_params
        params.require(:checkout_item).permit(:item_id)
    end
end

app/controllers/free_items_controller.rb
class FreeItemsController < ApplicationController
    def index
        @free_items = FreeItem.all        
    end
    
    def new
        @free_items = FreeItem.all        
        @free_item = FreeItem.new
    end

    def create
        @free_item = FreeItem.new(free_item_params)

        if @free_item.save
            redirect_to free_items_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @free_item = FreeItem.find(params[:id])
        @free_item.destroy
        redirect_to free_items_path, status: :see_other
    end

    private

    def free_item_params
        params.require(:free_item).permit(:quantity, :item_id, :free_item)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end

    def new
        @items = Item.all
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)

        if @item.save
            redirect_to catalog_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to catalog_path, status: :see_other
    end

    private

    def item_params
        params.require(:item).permit(:sku, :name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_checkout
    if Checkout.find_by_id(session[:checkout_id]).nil?
      Checkout.new
    else
      Checkout.find_by_id(session[:checkout_id])
    end
  end
end

app/helpers/bulk_orders_helper.rb
module BulkOrdersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_items_helper.rb
module CheckoutItemsHelper
end

app/helpers/free_items_helper.rb
module FreeItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bulk_orders/_bulk_order.html.erb
<div class="list-group-item" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            New Price: $<%= item.adjusted_price %>
        </h5>
        <small>
            <%= link_to "Remove", delete_bulk_order_path(item.id), data: { "turbo-method": :delete }, class: "text-decoration-none text-danger" %>
        </small>
    </div>
    <small>
        if you buy at least <%= item.min_quantity %> pc/s of <%= Item.find(item.item_id).name %>
    </small>
</div>

app/views/bulk_orders/index.html.erb
<div class="container-fluid w-75">
    <div class="d-flex flex-row justify-content-between align-items-center p-4">
        <div class="pe-2">
            <h1>Bulk Order Promos</h1>
        </div>
        <button type="button" class="btn btn-success">
            <%= link_to "Add New Promo", new_bulk_order_path, class: "text-white text-decoration-none" %>
        </button>
    </div>

    <div class="list-group">
        <% @bulk_orders.each do |item| %>
            <%= render "bulk_order", item: item %>
        <% end %>
    </div>
</div>

app/views/bulk_orders/new.html.erb
<div class="container-fluid w-75">
    <div class="d-flex flex-row justify-content-between align-items-center p-4">
        <div class="pe-2">
            <h1>Bulk Order Promos</h1>
        </div>
    </div>

    <div class="list-group">
        <% @bulk_orders.each do |item| %>
            <%= render "bulk_order", item: item %>
        <% end %>
    </div>

    <div class="list-group">
        <div class="list-group-item" aria-current="true">
            <%= form_with model: @bulk_order, url: create_bulk_order_path do |f| %>
                <h5 class="mb-1">
                    New Price:  $<%= f.number_field :adjusted_price, step: 0.01 %>
                </h5>
                <small>
                    if you buy at least <%= f.number_field :min_quantity, step: 1 %> pc/s of <%= f.select :item_id, options_for_select(Item.all.collect{ |item| [item.sku, item.id] }), {:prompt => "Choose from the available SKUs"}, {} %>
                </small>
                <div>
                    <%= f.submit "Add", class: "btn btn-outline-success" %>
                    <button type="button" class="btn btn-secondary col-sm-1 mx-2">
                        <%= link_to "Cancel", bulk_orders_path, class: "text-white text-decoration-none" %>
                    </button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/cart/show.html.erb
<div class="container-fluid w-75">
  <div class="d-flex flex-row justify-content-between align-items-center p-4">
    <div class="pe-2">
      <h1>Cart</h1>
    </div>
    <button type="button" class="btn btn-danger">
      <%= link_to "Clear All", reset_path, class: "text-white text-decoration-none" %>
    </button>
  </div>
  <%= form_with model: @checkout_item, url: create_checkout_item_path, class: "input-group" do |f| %>
    <%= f.select :item_id, options_for_select(Item.all.collect{ |item| [item.sku, item.id] }), {:prompt => "Choose from the available SKUs"},  {class: "form-select", id: "inputGroupSelect04"} %>
    <%= f.submit "Scan", class: "btn btn-outline-success" %>
  <% end %>
  
  <div class="list-group">
    <% @checkout_items.each do |checkout_item| %>
      <div class="list-group-item" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">
            <%= checkout_item.item.name %>
          </h5>
          <small>
            <%= link_to "Remove", delete_checkout_item_path(checkout_item.id), data: { "turbo-method": :delete }, class: "text-decoration-none text-danger" %>
          </small>
        </div>
        <p class="mb-1">
          $<%= checkout_item.item.price %>
        </p>
        <small>
          SKU: <%= checkout_item.item.sku %>
        </small>
      </div>
    <% end %>
  </div>

  <div class="list-group">
    <div class="list-group-item" aria-current="true">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
          Subtotal
        </h5>
        <h5>
          $<%= @checkout.subtotal %>
        </h5>
      </div>
      <small>
        (Total before promos are applied)
      </small>
    </div>
    <div class="list-group-item" aria-current="true">
      <div class="d-flex w-100 justify-content-between">
        <h3 class="mb-1">
          TOTAL
        </h3>
        <h3>
          $<%= @checkout.total %>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/free_items/_free_item.html.erb
<div class="list-group-item" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            Free: <%= Item.where(sku: item.free_item).first.name %>
        </h5>
        <small>
            <%= link_to "Remove", delete_free_item_path(item.id), data: { "turbo-method": :delete }, class: "text-decoration-none text-danger" %>
        </small>
    </div>
    <small>
        if you buy  <%= item.quantity %> pc/s of <%= Item.find(item.item_id).name %>
    </small>
</div>

app/views/free_items/index.html.erb
<div class="container-fluid w-75">
    <div class="d-flex flex-row justify-content-between align-items-center p-4">
        <div class="pe-2">
            <h1>Free Item Promos</h1>
        </div>
        <button type="button" class="btn btn-success">
            <%= link_to "Add New Promo", new_free_item_path, class: "text-white text-decoration-none" %>
        </button>
    </div>

    <div class="list-group">
        <% @free_items.each do |item| %>
            <%= render "free_item", item: item %>
        <% end %>
    </div>
</div>

app/views/free_items/new.html.erb
<div class="container-fluid w-75">
    <div class="d-flex flex-row justify-content-between align-items-center p-4">
        <div class="pe-2">
            <h1>Free Item Promos</h1>
        </div>
    </div>

    <div class="list-group">
        <% @free_items.each do |item| %>
            <%= render "free_item", item: item%>
        <% end %>
    </div>

    <div class="list-group">
        <div class="list-group-item" aria-current="true">
            <%= form_with model: @free_item, url: create_free_item_path do |f| %>
                <h5 class="mb-1">
                    Free:  <%= f.select :free_item, options_for_select(Item.all.collect{ |item| [item.sku] }), {:prompt => "Choose from the available SKUs"}, {} %>
                </h5>
                <small>
                    if you buy <%= f.number_field :quantity, step: 1 %> pc/s of <%= f.select :item_id, options_for_select(Item.all.collect{ |item| [item.sku, item.id] }), {:prompt => "Choose from the available SKUs"}, {} %>
                </small>
                <div>
                    <%= f.submit "Add", class: "btn btn-outline-success" %>
                    <button type="button" class="btn btn-secondary col-sm-1 mx-2">
                        <%= link_to "Cancel", free_items_path, class: "text-white text-decoration-none" %>
                    </button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/items/index.html.erb
<div class="container-fluid w-75">
  <div class="d-flex flex-row justify-content-between align-items-center p-4">
    <div class="pe-2">
      <h1>Catalog</h1>
    </div>
    <button type="button" class="btn btn-success">
      <%= link_to "Add New Item", new_item_path, class: "text-white text-decoration-none" %>
    </button>
  </div>

  <div class="table-responsive">
    <table class="table align-middle table-hover">
      <thead class="table-primary text-center">
        <tr>
          <th scope="col">id</th>
          <th scope="col">SKU</th>
          <th scope="col">Item Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <% @items.each do |item| %>
          <tr>
            <th scope="row"><%= item.id %></th>
            <td><%= item.sku %></td>
            <td><%= item.name %></td>
            <td>$<%= item.price %></td>
            <td>
              <button type="button" class="btn btn-danger">
                <%= link_to "Remove", delete_item_path(item.id), data: { "turbo-method": :delete }, class: "text-white text-decoration-none" %>
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/new.html.erb
<div class="container-fluid w-75">
  <div class="d-flex flex-row justify-content-start align-items-center p-4">
    <div class="pe-2">
      <h1>Catalog</h1>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table align-middle table-hover">
      <thead class="table-primary text-center">
        <tr>
          <th scope="col">id</th>
          <th scope="col">SKU</th>
          <th scope="col">Item Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <% @items.each do |item| %>
          <tr>
            <th scope="row"><%= item.id %></th>
            <td><%= item.sku %></td>
            <td><%= item.name %></td>
            <td>$<%= item.price %></td>
            <td>
              <button type="button" class="btn btn-danger">
                <%= link_to "Remove", delete_item_path(item.id), data: { "turbo-method": :delete }, class: "text-white text-decoration-none" %>
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= form_with model: @item, url: create_item_path do |f| %>
      <div class="row g-3">
        <div class="col-sm-3">
          <%= f.text_field :sku, class: "form-control", placeholder: "Enter unique SKU" %>
          <% @item.errors.full_messages_for(:sku).each do |message| %>
            <%= message %>
          <% end %>
        </div>
        <div class="col-sm">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter Item Name" %>
          <% @item.errors.full_messages_for(:name).each do |message| %>
            <%= message %>
          <% end %>
        </div>
        <div class="col-sm">
          <%= f.number_field :price, step: 0.01, class: "form-control", placeholder: "Enter Price" %>
          <% @item.errors.full_messages_for(:price).each do |message| %>
            <%= message %>
          <% end %>
        </div>
        <%= f.submit "Add", class: "btn btn-success col-sm-1 mx-2" %>
        <button type="button" class="btn btn-secondary col-sm-1 mx-2">
          <%= link_to "Cancel", catalog_path, class: "text-white text-decoration-none" %>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a clas="navbar-brand">
      <%= link_to "Checkout System", root_path, class: "navbar-brand" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" aria-current="page">
          <%= link_to "Cart", root_path, class: "navbar-brand" %>
        </a>
        <a class="nav-link">
          <%= link_to "Catalog", catalog_path, class: "navbar-brand" %>
        </a>
        <a class="nav-link">
          <%= link_to "Free Item", free_items_path, class: "navbar-brand" %>
        </a>
        <a class="nav-link">
          <%= link_to "Bulk Order", bulk_orders_path, class: "navbar-brand" %>
        </a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckoutSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</html>